[package]
name = "evm-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.21.2", features = ["full"] }
jsonrpsee-ws-client = "0.16.0"
anyhow = "1.0.66"
tokio-postgres = "0.7.7"
postgres-native-tls = "0.5.0"
native-tls = "0.2.11"
