[package]
name = "evm-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
diesel = { version = "2", features = ["postgres"] }
dotenv = "0.15"
log = "0.4"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
web3 = "0.18"
diesel_migrations = { version = "2", features = ["postgres"] }

[dependencies.simple_logger]
version = "4.0.0"
default-features = false
features = ["colors"]