[package]
name = "evm-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.21.2", features = ["full"] }
anyhow = "1.0.66"
tokio-postgres = "0.7.7"
tokio-pg-mapper = "0.2.0"
tokio-pg-mapper-derive = "0.2.0"
web3 = "0.18.0"
serde_json = "1.0.87"
log = "0.4.17"

[dependencies.simple_logger]
version = "4.0.0"
default-features = false
features = ["colors"]