[package]
name = "evm-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.21.2", features = ["full"] }
anyhow = "1.0.66"
web3 = "0.18.0"
serde_json = "1.0.87"
log = "0.4.17"
mongodb = "2.3.1"
serde = "1.0.147"

[dependencies.simple_logger]
version = "4.0.0"
default-features = false
features = ["colors"]
