[package]
name = "evm-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
web3 = "0.18.0"

[dependencies.mongodb]
version = "2.3.1"
default-features = false
features = ["tokio-sync"]
