services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indexerdb
    ports:
      - '5432:5432'
    volumes: 
      - /mnt/indexer_db/:/var/lib/postgresql/data
    networks:
      - postgres

  evm-indexer:
    init: true
    container_name: indexer
    image: ghcr.io/eabz/evm-indexer:latest
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/indexerdb
    env_file:
      - .env
    command: "evm-indexer"
    networks:
      - postgres
    depends_on:
      - "db"

networks:
  postgres:
    driver: bridge