services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=indexer
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=indexer
    volumes: 
      - ./database/:/var/lib/postgresql/data
    command: >
      -c work_mem=2GB
      -c max_wal_size=2GB  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres

  eth-indexer:
    container_name: eth-indexer
    image: ghcr.io/eabz/evm-indexer:latest
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://indexer:indexer@db/indexer
    env_file:
      - .env
    command: "evm-indexer"
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy

  polygon-indexer:
    container_name: polygon-indexer
    image: ghcr.io/eabz/evm-indexer:latest
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://indexer:indexer@db/indexer
    env_file:
      - .env
    command: "evm-indexer --chain polygon"
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy        
        
networks:
  postgres:
    driver: bridge