version: '3.8'
services:
  gnosis-node:
    init: true
    container_name: gnosis-node
    image: nethermind/nethermind
    user: root
    volumes:
      - ./gnosis/db:/nethermind/nethermind_db/
      - ./gnosis/keystore/:/nethermind/keystore
    environment:
      NETHERMIND_CONFIG: "xdai"
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES: "eth,subscribe,web3"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: "0.0.0.0"
      NETHERMIND_NETWORKCONFIG_ACTIVEPEERSMAXCOUNT: "256"
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"

    ports:
      - "8545:8545"
    restart: always    