services:
  ethereum:
    container_name: ethereum-node
    image: thorax/erigon:v2.30.0
    user: root
    command: |
      erigon
      --prune=hc
      --maxpeers 1000
      --db.pagesize=16k
      --datadir=/home/erigon/ethereum
      --http.api=eth,erigon,web3
      --ws
    volumes:
      - ./nodes/ethereum:/home/erigon/ethereum
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545

  gnosis:
    container_name: gnosis-node
    image: thorax/erigon:v2.30.0
    user: root
    command: |
      erigon
      --chain gnosis
      --prune=hc
      --maxpeers 1000
      --snapshots=false
      --db.pagesize=16k
      --datadir=/home/erigon/gnosis
      --http.api=eth,erigon,web3
      --ws
    volumes:
      - ./nodes/gnosis:/home/erigon/gnosis
    ports:
      - 30304:30303/tcp
      - 30304:30303/udp
      - 8546:8545