version: '3.7'

services:
  hasura:
    image: hasura/graphql-engine:latest
    container_name: indexer-hasura
    restart: always
    env_file:
      - .env
    network_mode: host
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${METADATA_DATABASE_URL}
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_PASSWORD}